# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMpxq4_xKIvgXAXChbxFjux-7mHxnG2m
"""

#LOGISTIC REGRESSION

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix, classification_report,
    roc_curve, auc, precision_recall_fscore_support
)
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load Dataset

df = pd.read_csv("titanic.csv")

# Clean minimal required columns
required_cols = ["Survived", "Pclass", "Sex", "Age", "Fare", "SibSp", "Parch"]
df = df[required_cols]

# Handle missing values
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Fare"].fillna(df["Fare"].median(), inplace=True)

# 2. Train / Validation / Test Split

X = df.drop("Survived", axis=1)
y = df["Survived"]

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)

# 3. Preprocessing Pipeline

numeric_features = ["Age", "Fare", "SibSp", "Parch"]
categorical_features = ["Sex", "Pclass"]

numeric_transformer = Pipeline(steps=[
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("encoder", OneHotEncoder(drop="first"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)


# 4. Final Model Pipeline

pipe = Pipeline(steps=[
    ("preprocess", preprocessor),
    ("model", LogisticRegression(max_iter=300, class_weight="balanced"))
])

# 5. Hyperparameter Tuning

param_grid = {
    "model__C": [0.01, 0.1, 1, 10],
    "model__penalty": ["l2"],
    "model__solver": ["lbfgs"]
}

grid = GridSearchCV(
    pipe,
    param_grid,
    cv=5,
    scoring="roc_auc",
    n_jobs=-1,
    verbose=1
)

grid.fit(X_train, y_train)

print("\nBest Parameters:", grid.best_params_)

best_model = grid.best_estimator_

# 6. Validation Set Evaluation

y_val_pred = best_model.predict(X_val)
y_val_prob = best_model.predict_proba(X_val)[:, 1]

print("\nClassification Report (Validation):")
print(classification_report(y_val, y_val_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

# 7. ROC Curve
fpr, tpr, thresholds = roc_curve(y_val, y_val_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(7,5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
plt.plot([0,1], [0,1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Validation ROC Curve")
plt.legend()
plt.show()

# 8. Threshold Tuning
thresholds_list = np.arange(0.1, 0.9, 0.05)

best_threshold = 0.5
best_f1 = 0

print("\nThreshold Tuning Results:")
for t in thresholds_list:
    preds = (y_val_prob >= t).astype(int)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_val, preds, average="binary"
    )
    print(f"Threshold={t:.2f} | Precision={precision:.3f} | Recall={recall:.3f} | F1={f1:.3f}")

    if f1 > best_f1:
        best_f1 = f1
        best_threshold = t

print("\nBest Threshold by F1:", best_threshold)

# 9. Feature Importance
feature_names = (
    numeric_features +
    list(best_model.named_steps["preprocess"]
         .named_transformers_["cat"]
         .named_steps["encoder"]
         .get_feature_names_out(categorical_features))
)

coefficients = best_model.named_steps["model"].coef_[0]

feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coefficients
}).sort_values(by="Coefficient", ascending=False)

print("\nFeature Importance:")
print(feature_importance)

plt.figure(figsize=(8,6))
sns.barplot(data=feature_importance, x="Coefficient", y="Feature")
plt.title("Feature Importance (Logistic Regression)")
plt.show()

